config/routes.rb
Rails.application.routes.draw do
  resources :solutions

  resources :questions

  resources :topics

  resources :course_modules

  resources :courses

  resources :years

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :year, :code, :credits, :period)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.slim
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      h2 = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      ul
        - @course.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :year
    = f.date_select :year
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :credits
    = f.number_field :credits
  .field
    = f.label :period
    = f.text_field :period
  .actions = f.submit

app/views/courses/edit.html.slim
h1 Editing course

== render 'form'

= link_to 'Show', @course
'|
= link_to 'Back', courses_path

app/views/courses/index.html.slim
h1 Listing courses

table
  thead
    tr
      th Name
      th Year
      th Code
      th Credits
      th Period
      th
      th
      th

  tbody
    - @courses.each do |course|
      tr
        td = course.name
        td = course.year
        td = course.code
        td = course.credits
        td = course.period
        td = link_to 'Show', course
        td = link_to 'Edit', edit_course_path(course)
        td = link_to 'Destroy', course, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Course', new_course_path

app/views/courses/new.html.slim
h1 New course

== render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.slim
p#notice = notice

p
  strong Name:
  = @course.name
p
  strong Year:
  = @course.year
p
  strong Code:
  = @course.code
p
  strong Credits:
  = @course.credits
p
  strong Period:
  = @course.period

= link_to 'Edit', edit_course_path(@course)
'|
= link_to 'Back', courses_path