config/routes.rb
Rails.application.routes.draw do
  resources :solutions

  resources :questions

  resources :topics

  resources :course_modules

  resources :courses

  resources :years

end

app/models/year.rb
class Year < ActiveRecord::Base
	has_many :courses
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: [:show, :edit, :update, :destroy]

  # GET /years
  # GET /years.json
  def index
    @years = Year.all
  end

  # GET /years/1
  # GET /years/1.json
  def show
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years
  # POST /years.json
  def create
    @year = Year.new(year_params)

    respond_to do |format|
      if @year.save
        format.html { redirect_to @year, notice: 'Year was successfully created.' }
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1
  # PATCH/PUT /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to @year, notice: 'Year was successfully updated.' }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1
  # DELETE /years/1.json
  def destroy
    @year.destroy
    respond_to do |format|
      format.html { redirect_to years_url, notice: 'Year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def year_params
      params.require(:year).permit(:name, :year)
    end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.slim
= form_for @year do |f|
  - if @year.errors.any?
    #error_explanation
      h2 = "#{pluralize(@year.errors.count, "error")} prohibited this year from being saved:"
      ul
        - @year.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :year
    = f.date_select :year
  .actions = f.submit

app/views/years/edit.html.slim
h1 Editing year

== render 'form'

= link_to 'Show', @year
'|
= link_to 'Back', years_path

app/views/years/index.html.slim
h1 Listing years

table
  thead
    tr
      th Name
      th Year
      th
      th
      th

  tbody
    - @years.each do |year|
      tr
        td = year.name
        td = year.year
        td = link_to 'Show', year
        td = link_to 'Edit', edit_year_path(year)
        td = link_to 'Destroy', year, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Year', new_year_path

app/views/years/new.html.slim
h1 New year

== render 'form'

= link_to 'Back', years_path

app/views/years/show.html.slim
p#notice = notice

p
  strong Name:
  = @year.name
p
  strong Year:
  = @year.year

= link_to 'Edit', edit_year_path(@year)
'|
= link_to 'Back', years_path